---

version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    depends_on:
    - nexus
    networks:
    - test
    ports: 
    - "80:8080"
  nexus:
    container_name: nexus
    build:
      context: .
      dockerfile: Dockerfile.nexus
    networks:
    - test
    ports: 
    - "81:8081"
networks:
  test: