# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus   = 2
    end

    config.vm.define "jenkins.vm", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.50.10"
        jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
        jenkins.vm.hostname = "jenkins.vm"
        jenkins.vm.provision "shell", inline: <<-SHELL
            #apt-get update #--allow-releaseinfo-change
            #apt-get install -y build-essential default-jre #git
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc
        SHELL
    end

    config.vm.define "master", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.11"
        master.vm.hostname = "master"
        master.vm.provider("virtualbox") { |vb| vb.memory = 512 }

        master.vm.provision :shell, inline: <<-SHELL
            apt-get update
            apt-get install -y vim ansible sshpass
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc
            cd /vagrant && ansible-playbook -i inventory playbook.yaml
        SHELL
    end

Vagrant.configure("2") do |config|
        config.vm.box = "debian/buster64"
    
        config.vm.define "staging.vm" do |host|
            host.vm.network "private_network", ip: "192.168.50.12"
            host.vm.hostname = "staging.vm"
            host.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
        end
    
        config.vm.define "production.vm" do |host|
            host.vm.network "private_network", ip: "192.168.50.13"
            host.vm.hostname = "production.vm"
            host.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
        end
    
        config.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            echo -e "vagrant\nvagrant" | passwd vagrant
        SHELL
    end

    Vagrant.configure("2") do |config|

        config.vm.box = "generic/debian11"
        config.vm.network "private_network", ip: "192.168.50.14"
        config.vm.hostname = "nexus.vm"
    
        config.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus   = 2
        end
    
        config.vm.provision "shell", inline: <<-SHELL
            apt-get update #--allow-releaseinfo-change
            apt-get install -y git build-essential default-jre
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc
        SHELL
    end
end