Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian9"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
    end

    config.vm.define "jenkins.vm", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.50.10"
        jenkins.vm.hostname = "jenkins.vm"
        jenkins.vm.provision "shell", inline: <<-SHELL
            apt-get update #--allow-releaseinfo-change
            #apt-get install -y #build-essential default-jre #git
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc
        SHELL
    end

    config.vm.define "master", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.11"
        master.vm.hostname = "master"
        master.vm.provider("virtualbox") { |vb| vb.memory = 512 }

        master.vm.provision :shell, inline: <<-SHELL
            apt-get update
            apt-get install -y vim ansible sshpass
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            echo "alias ll='ls -l'" >> /root/.bashrc
            #cd /vagrant && ansible-playbook -i inventory playbook.yaml
        SHELL
    end
end