---
- name: configure slave2
  hosts: slave2

  tasks:
  - name: Install apache2
    become: true
    apt:
      name:
      - apache2
      state: present

  - name: copy files
    become: true
    copy:
      src: /vagrant/index.html
      dest: /var/www/html/index.html

  - name: copy files
    become: true
    copy:
      src: /vagrant/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf

  - name: copy files
    become: true
    copy:
      src: /vagrant/ports.conf
      dest: /etc/apache2/ports.conf

  - name: Restart apache2
    become: true
    service:
      name: apache2
      state: restarted

- name: configure slave3
  hosts: slave3

  tasks:
  - name: Install Apache, php, libapache
    become: true
    apt:
      name:
      - apache2
      - php
      - libapache2-mod-php
      state: present

  - name: create directory
    become: true
    file:
      path=/var/www/php
      state=directory

  - name: copy files
    become: true
    copy:
      src: /vagrant/index.php
      dest: /var/www/php/index.php

  - name: copy files
    become: true
    copy:
      src: /vagrant/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf

  - name: copy files
    become: true
    copy:
      src: /vagrant/ports.conf
      dest: /etc/apache2/ports.conf

  - name: Restart apache2
    become: true
    service:
      name: apache2
      state: restarted

- name: configure slave1
  hosts: slave1

  tasks:
  - name: Install nginx
    become: true
    apt:
      name:
      - nginx
      state: present

  - name: copy files
    become: true
    copy:
      src: /vagrant/default
      dest: /etc/nginx/sites-available/default

  - name: Restart nginx
    become: true
    service:
      name: nginx
      state: restarted

