Vagrant.configure("2") do |config|
    config.vm.box = "montade/centos8denq"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    config.vm.network "private_network", ip: "192.168.33.11"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "centos8.vagrant.vm"
        # Customize the amount of memory on the VM:
        vb.memory = "512"
    end
    config.vm.provision "shell", inline: <<-SHELL
        sudo mkdir /var/www/html/ht /var/www/html/php
        sudo mkdir /var/log/httpd/ht /var/log/httpd/php
        sudo cp /vagrant/index.html /var/www/html/ht/ /var/www/html
        sudo cp /vagrant/index.php /var/www/html/php/
        sudo cp /vagrant/httpd.conf /etc/httpd/conf/httpd.conf
        sudo yum remove firewalld -y
        systemctl restart httpd
    SHELL
    #config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    #config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end
