---
- name: Ensure dependencies are installed.
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - build-essential
      - default-jre
      - git
      - jq
    state: present
    update_cache: yes

- name: add repository
  become: true
  shell:
    "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null"

- name: add repository
  become: true
  shell:
    "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null"

- name: Update the repository cache and install jenkins
  become: true
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: yes