name: hometask-10

on:
  push:
  workflow_dispatch:
  
jobs:
  hometask-10:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build wcg
        run: docker build --tag ghcr.io/${{ github.actor }}/wcg:latest -f ./07-docker/Dockerfile.multi .
      - name: latest tag
        run: docker push ghcr.io/${{ github.actor }}/wcg:latest
