name: hometask-10

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.16
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        repository: Denqe/word-cloud-generator
        
    - name: build wcg
      run: |
        make
        ls -l
        ls -l artifacts
